/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Position;

import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vutha.vyrapol
 */
public class AddPermission extends javax.swing.JPanel {

    DefaultTableModel addPTable;
    String id;

    private void refreshTable() {
        var permissions = Position.getAllPermissions();
        addPTable = (DefaultTableModel) addPermissionTable.getModel();
        addPTable.setRowCount(0);
        for (var permission : permissions) {
            Object[] data = new Object[6];
            data[0] = permission.get("id");
            data[1] = permission.get("name");
            data[2] = permission.get("read").equals(true) ? "Yes" : "No";
            data[3] = permission.get("create").equals(true) ? "Yes" : "No";
            data[4] = permission.get("update").equals(true) ? "Yes" : "No";
            data[5] = permission.get("delete").equals(true) ? "Yes" : "No";
            addPTable.addRow(data);
        }
    }

    /**
     * Creates new form AddPermission
     */
    public AddPermission() {
        initComponents();
        refreshTable();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbRead = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbCreate = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbUpdate = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbDelete = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addPermissionTable = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1);

        txtName.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtName.setText("Employee");
        jPanel2.add(txtName);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setText("Read");
        jPanel3.add(jLabel2);

        cbRead.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbRead.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel3.add(cbRead);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setText("Create");
        jPanel4.add(jLabel3);

        cbCreate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbCreate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel4.add(cbCreate);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setText("Update");
        jPanel6.add(jLabel4);

        cbUpdate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel6.add(cbUpdate);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel5.setText("Delete");
        jPanel7.add(jLabel5);

        cbDelete.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbDelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel7.add(cbDelete);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_LEADING;
        jPanel8.add(btnUpdate, gridBagConstraints);

        jPanel5.add(jPanel8);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        addPermissionTable.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        addPermissionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Permission", "Read", "Create", "Update", "Delete"
            }
        ));
        addPermissionTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        addPermissionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPermissionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(addPermissionTable);

        jPanel16.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPermissionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPermissionTableMouseClicked
        int row = addPermissionTable.getSelectedRow();
        id = addPermissionTable.getValueAt(row, 0).toString();
        txtName.setText(addPermissionTable.getValueAt(row, 1).toString());
        String read = addPermissionTable.getValueAt(row, 2).toString();
        String create = addPermissionTable.getValueAt(row, 3).toString();
        String update = addPermissionTable.getValueAt(row, 4).toString();
        String delete = addPermissionTable.getValueAt(row, 5).toString();
        cbRead.setSelectedItem(read);
        cbCreate.setSelectedItem(create);
        cbUpdate.setSelectedItem(update);
        cbDelete.setSelectedItem(delete);
    }//GEN-LAST:event_addPermissionTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int read = cbRead.getSelectedIndex() == 0 ? 1 : 0;
        int create = cbCreate.getSelectedIndex() == 0 ? 1 : 0;
        int update = cbUpdate.getSelectedIndex() == 0 ? 1 : 0;
        int delete = cbDelete.getSelectedIndex() == 0 ? 1 : 0;
        HashMap<String, String> message = Position.UpdatePermission(Integer.parseInt(id), read, create, update, delete);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable addPermissionTable;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbCreate;
    private javax.swing.JComboBox<String> cbDelete;
    private javax.swing.JComboBox<String> cbRead;
    private javax.swing.JComboBox<String> cbUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
