/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Position;

import Global.ComboItem;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vutha.vyrapol
 */
public class AssignPermission extends javax.swing.JPanel {
    
    DefaultTableModel assignPerTable;
    ArrayList<HashMap<String, Object>> permissions;
    ArrayList<HashMap<String, Object>> positions;
    Integer position_id;
    Integer permission_id;
    
    private void refreshTable() {
        var permissionsPositions = Position.getAllPermissionPosition();
        assignPerTable = (DefaultTableModel) assignPermissionTable.getModel();
        assignPerTable.setRowCount(0);
        for (var perPos : permissionsPositions) {
            Object[] data = new Object[2];
            data[0] = perPos.get("position_name");
            data[1] = perPos.get("permission_name");
            assignPerTable.addRow(data);
        }
    }

    /**
     * Creates new form AssignPermission
     */
    public AssignPermission() {
        initComponents();
        positions = Position.getAllPositions();
        permissions = Position.getAllPermissions();
        for (var position : positions) {
            cbPosition.addItem(new ComboItem(position.get("name").toString(), position.get("id").toString()));
        }
        for (var permission : permissions) {
            cbPermission.addItem(new ComboItem(permission.get("name").toString(), permission.get("id").toString()));
        }
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbPosition = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbPermission = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        assignPermissionTable = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setText("Position");
        jPanel4.add(jLabel3);
        jPanel4.add(cbPosition);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setText("Permission");
        jPanel5.add(jLabel4);
        jPanel5.add(cbPermission);

        jPanel1.add(jPanel5);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2);

        jPanel20.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnSave.setBackground(new java.awt.Color(0, 72, 217));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel20.add(btnSave);

        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel20.add(btnUpdate);

        jPanel3.add(jPanel20);

        jPanel1.add(jPanel3);

        jPanel16.setLayout(new java.awt.GridLayout());

        assignPermissionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Position Name", "Permission Name"
            }
        ));
        assignPermissionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignPermissionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(assignPermissionTable);

        jPanel16.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignPermissionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignPermissionTableMouseClicked
        int row = assignPermissionTable.getSelectedRow();
        int i = 0;
        int j = 0;
        for (var position : positions) {
            if (position.get("name").toString().equals(assignPerTable.getValueAt(row, 0).toString())) {
                position_id = Integer.parseInt(position.get("id").toString());
                cbPosition.setSelectedIndex(i);
            }
            i++;
        }
        for (var permission : permissions) {
            if (permission.get("name").toString().equals(assignPerTable.getValueAt(row, 1).toString())) {
                permission_id = Integer.parseInt(permission.get("id").toString());
                cbPermission.setSelectedIndex(j);
            }
            j++;
        }
    }//GEN-LAST:event_assignPermissionTableMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String position = ((ComboItem) cbPosition.getSelectedItem()).getValue();
        String permission = ((ComboItem) cbPermission.getSelectedItem()).getValue();
        HashMap<String, String> message = Position.AddPermissionPosition(Integer.parseInt(permission), Integer.parseInt(position));
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String position = ((ComboItem) cbPosition.getSelectedItem()).getValue();
        String permission = ((ComboItem) cbPermission.getSelectedItem()).getValue();
        HashMap<String, String> message = Position.UpdatePermissionPosition(permission_id, position_id, Integer.parseInt(permission), Integer.parseInt(position));
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assignPermissionTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<ComboItem> cbPermission;
    private javax.swing.JComboBox<ComboItem> cbPosition;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
