/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Trip;

import Login.DBCon;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.*;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yarith
 */
public class Route extends javax.swing.JPanel {

    Connection conn;
    Map<String, Integer> vehicle = new HashMap<>();
    ArrayList<String> locations = new ArrayList();

    /**
     * Creates new form Route2
     */
    public Route() {
        try {
            conn = DBCon.getConnection();
        } catch (SQLException e) {
        }
        initComponents();
        ComboBoxReload();
        cbOrigin.addItemListener(cbOriginChange());
        cbDestination.addItemListener(cbDestinationChange());
        tableReload();
        ((DefaultTableCellRenderer) jTblRoute.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.LEFT);
    }

    private ItemListener cbOriginChange() {
        return (e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                if (e.getItem().toString() != "Select") {
                    Object selected = cbDestination.getSelectedItem();
                    cbDestination.removeItemListener(cbDestination.getItemListeners()[0]);
                    cbDestination.removeAllItems();
                    List locationsList = new ArrayList(locations);
                    locationsList.remove(e.getItem().toString());
                    cbDestination.addItem("Select");
                    for (var location : locationsList) {
                        cbDestination.addItem(location.toString());
                    }
                    cbDestination.setSelectedItem(selected);
                    cbDestination.addItemListener(cbDestinationChange());
                }
            }
        };
    }

    private ItemListener cbDestinationChange() {
        return (e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                if (e.getItem().toString() != "Select") {
                    Object selected = cbOrigin.getSelectedItem();
                    cbOrigin.removeItemListener(cbOrigin.getItemListeners()[0]);
                    cbOrigin.removeAllItems();
                    List locationsList = new ArrayList(locations);
                    locationsList.remove(e.getItem().toString());
                    cbOrigin.addItem("Select");
                    for (var location : locationsList) {
                        cbOrigin.addItem(location.toString());
                    }
                    cbOrigin.setSelectedItem(selected);
                    cbOrigin.addItemListener(cbOriginChange());
                }
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbOrigin = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbDestination = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbVehicle = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rdbtnActive = new javax.swing.JRadioButton();
        rdbtnInactive = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRoute = new javax.swing.JTable();

        jPanel2.setLayout(new java.awt.GridLayout(2, 3, 20, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Name");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtName)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Origin");

        cbOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 261, Short.MAX_VALUE))
            .addComponent(cbOrigin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Destination");

        cbDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 233, Short.MAX_VALUE))
            .addComponent(cbDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Vehicle Type");

        cbVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 224, Short.MAX_VALUE))
            .addComponent(cbVehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Price");

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 266, Short.MAX_VALUE))
            .addComponent(txtPrice)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Status");

        buttonGroup1.add(rdbtnActive);
        rdbtnActive.setText("Active");

        buttonGroup1.add(rdbtnInactive);
        rdbtnInactive.setText("Inactive");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(rdbtnActive)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnInactive)))
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnActive)
                    .addComponent(rdbtnInactive))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);

        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 72, 217));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTblRoute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Vehicle_Type_ID", "Name", "Origin", "Destination", "Price", "Status", "Created_at", "Updated_at"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblRoute.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblRoute);
        if (jTblRoute.getColumnModel().getColumnCount() > 0) {
            jTblRoute.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTblRoute.getColumnModel().getColumn(0).setMaxWidth(100);
            jTblRoute.getColumnModel().getColumn(6).setMaxWidth(110);
            jTblRoute.getColumnModel().getColumn(7).setMaxWidth(120);
            jTblRoute.getColumnModel().getColumn(8).setMaxWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addGap(23, 23, 23)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = jTblRoute.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row.");
            return;
        }
        Integer id = Integer.parseInt(jTblRoute.getValueAt(row, 0).toString());
        String vehicle_type = jTblRoute.getValueAt(row, 1).toString();
        String name = jTblRoute.getValueAt(row, 2).toString();
        String origin = jTblRoute.getValueAt(row, 3).toString();
        String destination = jTblRoute.getValueAt(row, 4).toString();
        String price = jTblRoute.getValueAt(row, 5).toString();
        Integer status = Integer.parseInt(jTblRoute.getValueAt(row, 6).toString());
        new UpdateRoute(this, vehicle, id, name, vehicle_type, origin, destination, price, status).setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String vehicle_selected = cbVehicle.getSelectedItem().toString();
        Integer vehicle_type_id = vehicle.get(vehicle_selected);
        String origin = cbOrigin.getSelectedItem().toString();
        String destination = cbDestination.getSelectedItem().toString();
        double price = 0;
        Integer status = 0;
        String name = txtName.getText();
        if (rdbtnActive.isSelected()) {
            status = 1;
        } else if (!rdbtnInactive.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select status.");
            return;
        }
        if (txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Name can't be empty");
            return;
        }
        try {
            price = Double.parseDouble(txtPrice.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price has to be integer or decimal number.");
            return;
        }
        rowInsert(name, vehicle_type_id, origin, destination, price, status);
        tableReload();
        txtName.setText("");
        txtPrice.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void rowInsert(String name, Integer vehicle_type_id, String origin, String destination, double price, Integer status) {
        try {
            String query = "INSERT INTO route (name, vehicle_type_id, origin, "
                    + "destination, price, status) VALUES (?,?,?,?,?,?)";
            PreparedStatement prepSt = conn.prepareStatement(query);
            prepSt.setString(1, name);
            prepSt.setInt(2, vehicle_type_id);
            prepSt.setString(3, origin);
            prepSt.setString(4, destination);
            prepSt.setDouble(5, price);
            prepSt.setInt(6, status);
            prepSt.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error occur during adding a "
                    + "route.\nPlease contact administrator.");
            e.printStackTrace(System.err);
        }
    }

    private void ComboBoxReload() {
        cbDestination.removeAllItems();
        cbOrigin.removeAllItems();
        cbVehicle.removeAllItems();
        vehicle = new HashMap<>();
        try {
            Statement st = conn.createStatement();
            String query = "SELECT name FROM location WHERE status=1";
            ResultSet rs = st.executeQuery(query);
            cbDestination.addItem("Select");
            cbOrigin.addItem("Select");
            while (rs.next()) {
                String name = rs.getString("name");
                cbDestination.addItem(name);
                cbOrigin.addItem(name);
                locations.add(name);
            }
            query = "SELECT id, type FROM vehicle_type WHERE status=1";
            rs = st.executeQuery(query);
            while (rs.next()) {
                vehicle.put(rs.getString("type"), rs.getInt("id"));
                cbVehicle.addItem(rs.getString("type"));
            }
            st.close();
        } catch (SQLException e) {

        }
    }

    public void tableReload() {
        DefaultTableModel tblModel = (DefaultTableModel) jTblRoute.getModel();
        tblModel.setRowCount(0);
        try {
            Statement st = conn.createStatement();
            String query = "SELECT * FROM route";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
//(id,vehicle,type_id,name,origin,destination,price,status,created_at,updated_at)
                Integer id = rs.getInt("id");
                String vehicle_type = "";
                for (String s : vehicle.keySet()) {
                    if (vehicle.get(s) == rs.getInt("vehicle_type_id")) {
                        vehicle_type = s;
                    }
                }
                String name = rs.getString("name");
                String origin = rs.getString("origin");
                String destination = rs.getString("destination");
                double price = rs.getDouble("price");
                Integer status = rs.getInt("status");
                String created_at = rs.getString("created_at");
                String updated_at = rs.getString("updated_at");
                Object[] row = {id, vehicle_type, name, origin, destination, price, status, created_at, updated_at};
                tblModel.addRow(row);
            }
            st.close();
        } catch (SQLException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDestination;
    private javax.swing.JComboBox<String> cbOrigin;
    private javax.swing.JComboBox<String> cbVehicle;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblRoute;
    private javax.swing.JRadioButton rdbtnActive;
    private javax.swing.JRadioButton rdbtnInactive;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
