/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Trip;

import Login.DBCon;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.github.lgooddatepicker.components.TimePickerSettings;
import java.awt.Dimension;
import java.sql.*;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yarith
 */
public class Trip extends javax.swing.JPanel {

    Connection conn;
    Map<String, Integer> drivers = new HashMap<>();
    Map<String, Integer> routes = new HashMap<>();
    Map<String, Integer> vehicles = new HashMap<>();
    DateTimePicker departure;
    DateTimePicker arrival;

    public Trip() {
        try {
            this.conn = DBCon.getConnection();
        } catch (SQLException e) {
        }
        initComponents();
        ((DefaultTableCellRenderer) jTblTrip.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.LEFT);
        reloadComboBox();
        reloadTable();

        TimePickerSettings timeSettings = new TimePickerSettings();
        timeSettings.use24HourClockFormat();
        departure = new DateTimePicker(null, timeSettings);
        arrival = new DateTimePicker(null, timeSettings);
        departure.setSize(new Dimension(400, 37));
        arrival.setSize(new Dimension(400, 37));
        jPanel11.add(departure);
        jPanel13.add(arrival);
    }

    /**
     * Creates new form Trip
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbDriver = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbVehicle = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbRoute = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rdbtnActive = new javax.swing.JRadioButton();
        rdbtnInactive = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblTrip = new javax.swing.JTable();

        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 72, 217));
        btnSave.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 15, 0));

        jLabel10.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel10.setText("Driver");

        cbDriver.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbDriver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(cbDriver, 0, 243, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);

        jLabel8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel8.setText("Vehicle");

        cbVehicle.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(cbVehicle, 0, 243, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);

        jLabel7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel7.setText("Route");

        cbRoute.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbRoute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 205, Short.MAX_VALUE))
            .addComponent(cbRoute, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel5.setText("Departure Time");

        jPanel11.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jLabel11.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel11.setText("Arrival Time");

        jPanel13.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 165, Short.MAX_VALUE))
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jLabel6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel6.setText("Status");

        buttonGroup1.add(rdbtnActive);
        rdbtnActive.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        rdbtnActive.setText("Active");

        buttonGroup1.add(rdbtnInactive);
        rdbtnInactive.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        rdbtnInactive.setText("Inactive");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdbtnActive)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnInactive)))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnActive)
                    .addComponent(rdbtnInactive))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        jTblTrip.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jTblTrip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Vehicle", "Route", "Driver", "Departure Time", "Arrival Time", "Status", "Created_at", "Updated_at"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblTrip.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblTrip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = jTblTrip.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row.");
            return;
        }
        Integer id = Integer.parseInt(jTblTrip.getValueAt(row, 0).toString());
        String vehicle_name = jTblTrip.getValueAt(row, 1).toString();
        String route_name = jTblTrip.getValueAt(row, 2).toString();
        String driver_name = jTblTrip.getValueAt(row, 3).toString();
        String departure_datetime = jTblTrip.getValueAt(row, 4).toString();
        String arrival_datetime = jTblTrip.getValueAt(row, 5).toString();
        Integer status = Integer.parseInt(jTblTrip.getValueAt(row, 6).toString());
        UpdateTrip updateTrip = new UpdateTrip(this, id, vehicle_name, driver_name, route_name, departure_datetime, arrival_datetime, status);
        updateTrip.setVisible(true);
        updateTrip.setMapsForComboxBox(drivers, routes, vehicles);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String selectedVehicle = cbVehicle.getSelectedItem().toString();
        String selectedRoute = cbRoute.getSelectedItem().toString();
        String selectedDriver = cbDriver.getSelectedItem().toString();

        Integer vehicle_id = vehicles.get(selectedVehicle);
        Integer route_id = routes.get(selectedRoute);
        Integer driver_id = drivers.get(selectedDriver);

        Integer status = 0;

        String d_date = departure.getDatePicker().getDate().format(DateTimeFormatter.ISO_LOCAL_DATE);
        String d_time = departure.getTimePicker().getText();
        String d_datetime = d_date + " " + d_time + ":00";
        Timestamp departureTimestamp = Timestamp.valueOf(d_datetime);

        String a_date = arrival.getDatePicker().getDate().format(DateTimeFormatter.ISO_LOCAL_DATE);
        String a_time = arrival.getTimePicker().getText();
        String a_datetime = a_date + " " + a_time + ":00";

        Timestamp arrivalTimestamp = Timestamp.valueOf(a_datetime);

        if (rdbtnActive.isSelected()) {
            status = 1;
        } else if (!rdbtnInactive.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select status.");
            return;
        }
        rowInsert(driver_id, route_id, vehicle_id, departureTimestamp, arrivalTimestamp, status);
        reloadTable();
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void rowInsert(Integer driver_id, Integer route_id, Integer vehicle_id, Timestamp departure, Timestamp arrival, Integer status) {
        try {
            String query = "INSERT INTO trip (vehicle_id, route_id, driver_id, start_date, end_date, status, sold_ticket, total_income)"
                    + "VALUES (?, ?, ?, ?, ?, ?,0,0)";
            PreparedStatement prepSt = conn.prepareStatement(query);
            prepSt.setInt(1, vehicle_id);
            prepSt.setInt(2, route_id);
            prepSt.setInt(3, driver_id);
            prepSt.setTimestamp(4, departure);
            prepSt.setTimestamp(5, arrival);
            prepSt.setInt(6, status);
            prepSt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
    }

    public void reloadTable() {
        DefaultTableModel tblModel = (DefaultTableModel) jTblTrip.getModel();
        tblModel.setRowCount(0);
        try {
            Statement st = conn.createStatement();
            String query = "SELECT * FROM trip";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
//(id,vehicle,type_id,name,origin,destination,price,status,created_at,updated_at)
                Integer id = rs.getInt("id");
                String vehicle_name = "";
                String route_name = "";
                String driver_name = "";
                for (String vehicle : vehicles.keySet()) {
                    Integer vehicle_id = vehicles.get(vehicle) == 1 ? 11 : 12;
                    if (vehicle_id == rs.getInt("vehicle_id")) {
                        vehicle_name = vehicle;
                        break;
                    }
                }
                for (String route : routes.keySet()) {
                    Integer route_id = routes.get(route);
                    if (route_id == rs.getInt("route_id")) {
                        route_name = route;
                        break;
                    }
                }
                for (String driver : drivers.keySet()) {
                    Integer driver_id = drivers.get(driver);
                    if (driver_id == rs.getInt("driver_id")) {
                        driver_name = driver;
                        break;
                    }
                }
                String departureTime = rs.getString("start_date");
                String arrivalTime = rs.getString("end_date");
                Integer status = rs.getInt("status");
                String created_at = rs.getString("created_at");
                String updated_at = rs.getString("updated_at");
                Object[] row = {id, vehicle_name, route_name, driver_name, departureTime, arrivalTime, status, created_at, updated_at};
                tblModel.addRow(row);
            }
            st.close();
        } catch (SQLException e) {
        }
    }

    private void reloadComboBox() {
        cbDriver.removeAllItems();
        cbRoute.removeAllItems();
        cbVehicle.removeAllItems();
        drivers = new HashMap<>();
        vehicles = new HashMap<>();
        routes = new HashMap<>();
        try {
            Statement st = conn.createStatement();
            String query = "SELECT id, first_name, last_name FROM staff WHERE position_id=9 and is_active=1";
            ResultSet rs = st.executeQuery(query);
            // iterate driver name, add to map
            while (rs.next()) {
                String full_name = rs.getString("first_name") + rs.getString("last_name");
                drivers.put(full_name, rs.getInt("id"));
                cbDriver.addItem(full_name);
            }

            query = "SELECT id, model FROM vehicle WHERE is_active=1";
            rs = st.executeQuery(query);
            // iterate vehicles
            while (rs.next()) {
                vehicles.put(rs.getString("model"), rs.getInt("id"));
                cbVehicle.addItem(rs.getString("model"));
            }

            query = "SELECT id, name FROM route WHERE status=1";
            rs = st.executeQuery(query);
            // iterate routes
            while (rs.next()) {
                routes.put(rs.getString("name"), rs.getInt("id"));
                cbRoute.addItem(rs.getString("name"));
            }
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
        // driver
        // vehicle
        // route, name
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDriver;
    private javax.swing.JComboBox<String> cbRoute;
    private javax.swing.JComboBox<String> cbVehicle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblTrip;
    private javax.swing.JRadioButton rdbtnActive;
    private javax.swing.JRadioButton rdbtnInactive;
    // End of variables declaration//GEN-END:variables
}
