/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vehicle;

import Global.ComboItem;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vutha.vyrapol
 */
public class Vehicle extends javax.swing.JPanel {
    
DefaultTableModel vTable;
    int id;
    ArrayList<HashMap<String, Object>> vehicleTypes;
    /**
     * Creates new form Vehicle
     */
    private void refreshTable() {
        var vehicles = VehicleClass.getAllVehicles();
        vTable = (DefaultTableModel) vehicleTable.getModel();
        vTable.setRowCount(0);
        for (var vehicle : vehicles) {
            Object[] data = new Object[6];
            data[0] = vehicle.get("id");
            data[1] = vehicle.get("model");
            data[2] = vehicle.get("type");
            data[3] = vehicle.get("plate_no");
            data[4] = vehicle.get("total_seat");
            data[5] = vehicle.get("is_active").equals(true) ? "Yes" : "No";
            vTable.addRow(data);
        }
    }
    
    public Vehicle() {
        initComponents();
        vehicleTypes = VehicleClass.getVehicleTypes();
        for (var vType : vehicleTypes) {
            cbVType.addItem(new ComboItem(vType.get("type").toString(), vType.get("id").toString()));
        }
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbVType = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPlate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSeat = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        activeY = new javax.swing.JRadioButton();
        activeN = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel1.setText("Model");
        jPanel2.add(jLabel1);

        txtModel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtModel.setText("V15-60");
        jPanel2.add(txtModel);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setText("Vehicle Type");
        jPanel3.add(jLabel2);

        cbVType.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jPanel3.add(cbVType);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setText("Plate No");
        jPanel4.add(jLabel3);

        txtPlate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtPlate.setText("0");
        jPanel4.add(txtPlate);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setText("Number of Seats");
        jPanel6.add(jLabel4);

        txtSeat.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtSeat.setText("20");
        jPanel6.add(txtSeat);

        jPanel5.add(jPanel6);

        jPanel12.setLayout(new java.awt.GridLayout(2, 0));

        jLabel9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel9.setText("Is Active");
        jPanel12.add(jLabel9);
        jPanel12.add(jPanel14);

        buttonGroup1.add(activeY);
        activeY.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        activeY.setSelected(true);
        activeY.setText("Yes");
        activeY.setActionCommand("1");
        jPanel12.add(activeY);

        buttonGroup1.add(activeN);
        activeN.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        activeN.setText("No");
        activeN.setActionCommand("0");
        jPanel12.add(activeN);

        jPanel5.add(jPanel12);

        jPanel8.setLayout(new java.awt.GridLayout(2, 0));
        jPanel5.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11, new java.awt.GridBagConstraints());

        jPanel19.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnSave.setBackground(new java.awt.Color(0, 72, 217));
        btnSave.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel19.add(btnSave);

        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel19.add(btnUpdate);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel9.add(jPanel19, gridBagConstraints);

        jPanel16.setLayout(new java.awt.GridLayout());

        vehicleTable.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Model", "Type", "Plate No", "Total Seats", "Is Active"
            }
        ));
        vehicleTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        vehicleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vehicleTable);

        jPanel16.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String model = txtModel.getText();
        String type = ((ComboItem) cbVType.getSelectedItem()).getValue();
        String plate = txtPlate.getText();
        int seat = Integer.parseInt(txtSeat.getText());
        String is_active = buttonGroup1.getSelection().getActionCommand();
        HashMap<String, String> message = VehicleClass.AddVehicle(type, plate, model, seat, is_active);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String model = txtModel.getText();
        String type = ((ComboItem) cbVType.getSelectedItem()).getValue();
        String plate = txtPlate.getText();
        int seat = Integer.parseInt(txtSeat.getText());
        String is_active = buttonGroup1.getSelection().getActionCommand();
        HashMap<String, String> message = VehicleClass.UpdateVehicle(id, type, plate, model, seat, is_active);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void vehicleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleTableMouseClicked
        // TODO add your handling code here:
        int row = vehicleTable.getSelectedRow();
        id = Integer.parseInt(vTable.getValueAt(row, 0).toString());
        txtModel.setText(vTable.getValueAt(row, 1).toString());
        for (var vType : vehicleTypes) {
            if (vType.get("type").toString().equals(vTable.getValueAt(row, 2).toString())) {
                cbVType.setSelectedItem(new ComboItem(vType.get("type").toString(), vType.get("id").toString()));
            }
        }
        txtPlate.setText(vTable.getValueAt(row, 3).toString());
        txtSeat.setText(vTable.getValueAt(row, 4).toString());
        if (vTable.getValueAt(row, 5).toString().equals("Yes")) {
            activeY.setSelected(true);
        } else {
            activeN.setSelected(true);
        }
    }//GEN-LAST:event_vehicleTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeN;
    private javax.swing.JRadioButton activeY;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<ComboItem> cbVType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables
}
