/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employee;

import Global.Helper;
import Global.MenuBar;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vutha.vyrapol
 */
public class Account extends javax.swing.JFrame {

    DefaultTableModel empTable;
    String id;
    ArrayList<HashMap<String, Object>> positions;
    public static JFrame frame;
    public static JPanel firstPanel;
    public static JPanel secondPanel;

    private void refreshTable() {
        var employees = Employee.getAllEmployees();
        int i = 0;
        empTable = (DefaultTableModel) employeeTable.getModel();
        empTable.setRowCount(0);
        for (var employee : employees) {
            Object[] data = new Object[10];
            data[0] = employee.get("id");
            data[1] = employee.get("first_name");
            data[2] = employee.get("last_name");
            data[3] = Helper.toUpperCase(employee.get("position").toString());
            data[4] = employee.get("email");
            data[5] = employee.get("mobile");
            data[6] = employee.get("address");
            data[7] = employee.get("salary");
            data[8] = employee.get("can_login").equals(true) ? "Yes" : "No";
            data[9] = employee.get("is_active").equals(true) ? "Yes" : "No";
            empTable.addRow(data);
            i++;
        }
    }

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
        frame = this;
        frame.setTitle("Home");
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        firstPanel = this.contentPanel;
        secondPanel = this.mainPanel;
        menu.add(MenuBar.createMenu(User.User.getCurrentInstance().getPosition()));
        positions = Position.Position.getAllPositions();
        for (var position : positions) {
            cbPosition.addItem(new ComboItem(Helper.toUpperCase(position.get("name").toString()), position.get("id").toString()));
        }
        refreshTable();
        // positions.get(INDEX).get(KEY)
        // first get is arraylist, second get is hashmap key`
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        login_group = new javax.swing.ButtonGroup();
        active_group = new javax.swing.ButtonGroup();
        contentPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbPosition = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        loginY = new javax.swing.JRadioButton();
        loginN = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        activeY = new javax.swing.JRadioButton();
        activeN = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jPanel19 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        menu = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        contentPanel.setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("First Name");
        jPanel2.add(jLabel1);

        txtFirstName.setText("John");
        jPanel2.add(txtFirstName);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("Last Name");
        jPanel3.add(jLabel2);

        txtLastName.setText("Doe");
        jPanel3.add(txtLastName);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setText("Position");
        jPanel4.add(jLabel3);

        jPanel4.add(cbPosition);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setText("Email");
        jPanel6.add(jLabel4);

        txtEmail.setText("john@city.travel.com");
        jPanel6.add(txtEmail);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setText("Password");
        jPanel7.add(jLabel5);

        txtPassword.setText("1234qwer");
        jPanel7.add(txtPassword);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jLabel6.setText("Mobile");
        jPanel8.add(jLabel6);

        txtMobile.setText("012345678");
        jPanel8.add(txtMobile);

        jPanel5.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel10.setLayout(new java.awt.GridLayout(2, 0));

        jLabel7.setText("Salary");
        jPanel10.add(jLabel7);

        txtSalary.setFont(txtSalary.getFont());
        txtSalary.setText("150");
        jPanel10.add(txtSalary);

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        jLabel8.setText("Can Login");
        jPanel11.add(jLabel8);
        jPanel11.add(jPanel13);

        login_group.add(loginY);
        loginY.setText("Yes");
        loginY.setActionCommand("1");
        jPanel11.add(loginY);

        login_group.add(loginN);
        loginN.setSelected(true);
        loginN.setText("No");
        loginN.setActionCommand("0");
        jPanel11.add(loginN);

        jPanel9.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(2, 0));

        jLabel9.setText("Is Active");
        jPanel12.add(jLabel9);
        jPanel12.add(jPanel14);

        active_group.add(activeY);
        activeY.setText("Yes");
        activeY.setActionCommand("1");
        jPanel12.add(activeY);

        active_group.add(activeN);
        activeN.setSelected(true);
        activeN.setText("No");
        activeN.setActionCommand("0");
        jPanel12.add(activeN);

        jPanel9.add(jPanel12);

        jPanel15.setLayout(new java.awt.GridBagLayout());

        jPanel17.setLayout(new java.awt.GridLayout(2, 0));

        jLabel11.setText("Address");
        jPanel17.add(jLabel11);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel17.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel15.add(jPanel17, gridBagConstraints);

        jPanel19.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnSave.setBackground(new java.awt.Color(0, 72, 217));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel19.add(btnSave);

        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel19.add(btnUpdate);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        jPanel15.add(jPanel19, gridBagConstraints);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "First Name", "Last Name", "Position", "Email", "Mobile", "Address", "Salary", "Can Login", "Active"
            }
        ));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(employeeTable);

        jPanel16.add(jScrollPane2);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        contentPanel.add(mainPanel);

        getContentPane().add(contentPanel);

        menu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        int row = employeeTable.getSelectedRow();
        id = empTable.getValueAt(row, 0).toString();
        txtFirstName.setText(empTable.getValueAt(row, 1).toString());
        txtLastName.setText(empTable.getValueAt(row, 2).toString());
        for (var position : positions) {
            if (position.get("name").toString().equals(empTable.getValueAt(row, 3).toString())) {
                cbPosition.setSelectedItem(new ComboItem(position.get("name").toString(), position.get("id").toString()));
            }
        }
        txtEmail.setText(empTable.getValueAt(row, 4).toString());
        txtPassword.setText("");
        txtMobile.setText(empTable.getValueAt(row, 5).toString());
        Object address = empTable.getValueAt(row, 6);
        txtAddress.setText(address == null ? "" : address.toString());
        txtSalary.setText(empTable.getValueAt(row, 7).toString());
        if (empTable.getValueAt(row, 8).toString().equals("Yes")) {
            loginY.setSelected(true);
        } else {
            loginN.setSelected(false);
        }
        if (empTable.getValueAt(row, 9).toString().equals("Yes")) {
            activeY.setSelected(true);
        } else {
            activeN.setSelected(false);
        }
    }//GEN-LAST:event_employeeTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String position = ((ComboItem) cbPosition.getSelectedItem()).getValue();
        String email = txtEmail.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String mobile = txtMobile.getText();
        String salary = txtSalary.getText();
        String can_login = login_group.getSelection().getActionCommand();
        String is_active = active_group.getSelection().getActionCommand();
        String address = txtAddress.getText();
        HashMap<String, String> message = Employee.UpdateEmployee(id, firstName, lastName, position, email, password, mobile, salary, address, can_login, is_active);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String position = ((ComboItem) cbPosition.getSelectedItem()).getValue();
        String email = txtEmail.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String mobile = txtMobile.getText();
        String salary = txtSalary.getText();
        String can_login = login_group.getSelection().getActionCommand();
        String is_active = active_group.getSelection().getActionCommand();
        String address = txtAddress.getText();
        HashMap<String, String> message = Employee.AddEmployee(firstName, lastName, position, email, password, mobile, salary, address, can_login, is_active);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeN;
    private javax.swing.JRadioButton activeY;
    private javax.swing.ButtonGroup active_group;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<ComboItem> cbPosition;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton loginN;
    private javax.swing.JRadioButton loginY;
    private javax.swing.ButtonGroup login_group;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
