/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Employee;

import Global.ComboItem;
import Global.Helper;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vutha.vyrapol
 */
public class Attendance extends javax.swing.JPanel {
    DefaultTableModel attTable;
    String id;
    ArrayList<HashMap<String, Object>> staffs;
    
    private void refreshTable() {
        var attendances = AttendanceClass.getAllAttendance();
        attTable = (DefaultTableModel) attendanceTable.getModel();
        attTable.setRowCount(0);
        for (var attendance : attendances) {
            Object[] data = new Object[5];
            data[0] = attendance.get("id");
            data[1] = attendance.get("first_name");
            data[2] = attendance.get("last_name");
            data[3] = attendance.get("status").equals(true) ? "Attend" : "Absence";
            data[4] = attendance.get("date");
            attTable.addRow(data);
        }
    }

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
        staffs = Employee.getAllEmployees();
        for (var staff : staffs) {
            cbStaff.addItem(new ComboItem(Helper.toUpperCase(staff.get("last_name").toString() + ' ' + Helper.toUpperCase(staff.get("first_name").toString())), staff.get("id").toString()));
        }
        refreshTable();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        attendanceGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbStaff = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        attendY = new javax.swing.JRadioButton();
        attendN = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dDate = new com.github.lgooddatepicker.components.DatePicker();
        jPanel15 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setText("Staff");
        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel4.add(jLabel3);

        cbStaff.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jPanel4.add(cbStaff);

        jPanel1.add(jPanel4);

        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        jLabel8.setText("Attendance");
        jLabel8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel11.add(jLabel8);
        jPanel11.add(jPanel13);

        attendanceGroup.add(attendY);
        attendY.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        attendY.setSelected(true);
        attendY.setText("Attend");
        attendY.setActionCommand("1");
        attendY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendYActionPerformed(evt);
            }
        });
        jPanel11.add(attendY);

        attendanceGroup.add(attendN);
        attendN.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        attendN.setText("Absence");
        attendN.setActionCommand("0");
        jPanel11.add(attendN);

        jPanel1.add(jPanel11);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("Date");
        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel3.add(jLabel2);

        dDate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jPanel3.add(dDate);

        jPanel1.add(jPanel3);

        jPanel15.setLayout(new java.awt.GridBagLayout());

        jPanel19.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnSave.setText("Save");
        btnSave.setBackground(new java.awt.Color(0, 72, 217));
        btnSave.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel19.add(btnSave);

        btnUpdate.setText("Update");
        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel19.add(btnUpdate);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel15.add(jPanel19, gridBagConstraints);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "First Name", "Last Name", "Attendance", "Date"
            }
        ));
        attendanceTable.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        attendanceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        attendanceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(attendanceTable);

        jPanel16.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String empId = ((ComboItem) cbStaff.getSelectedItem()).getValue();
        String isAttend = attendanceGroup.getSelection().getActionCommand();
        String date = dDate.getDate().toString();
        HashMap<String, String> message = AttendanceClass.AddAttendance(empId, isAttend, date);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String empId = ((ComboItem) cbStaff.getSelectedItem()).getValue();
        String isAttend = attendanceGroup.getSelection().getActionCommand();
        String date = dDate.getDate().toString();
        HashMap<String, String> message = AttendanceClass.UpdateAttendance(id, empId, isAttend, date);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void attendanceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceTableMouseClicked
        int row = attendanceTable.getSelectedRow();
        id = attendanceTable.getValueAt(row, 0).toString();
        int index = 0;
        for (var staff : staffs) {
            if (staff.get("first_name").toString().equals(attendanceTable.getValueAt(row, 1).toString()) && staff.get("last_name").toString().equals(attendanceTable.getValueAt(row, 2).toString())) {
                cbStaff.setSelectedIndex(index);
            }
            index++;
        }
        if (attendanceTable.getValueAt(row, 3).toString().equals("Attend")) {
            attendY.setSelected(true);
        } else {
            attendN.setSelected(false);
        }
        LocalDate thisDate = LocalDate.parse(attendanceTable.getValueAt(row, 4).toString());
        dDate.setDate(thisDate);
    }//GEN-LAST:event_attendanceTableMouseClicked

    private void attendYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendYActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton attendN;
    private javax.swing.JRadioButton attendY;
    private javax.swing.ButtonGroup attendanceGroup;
    private javax.swing.JTable attendanceTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<ComboItem> cbStaff;
    private com.github.lgooddatepicker.components.DatePicker dDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
