/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Employee;

import Global.ComboItem;
import Global.Helper;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vutha.vyrapol
 */
public class Payroll extends javax.swing.JPanel {

    DefaultTableModel pTable;
    String id;
    ArrayList<HashMap<String, Object>> staffs;

    private void refreshTable() {
        var payrolls = PayrollClass.getAllPayrolls();
        pTable = (DefaultTableModel) payrollTable.getModel();
        pTable.setRowCount(0);
        for (var payroll : payrolls) {
            Object[] data = new Object[9];
            data[0] = payroll.get("id");
            data[1] = String.format("%s %s", Helper.toUpperCase(payroll.get("last_name").toString()), Helper.toUpperCase(payroll.get("first_name").toString()));
            data[2] = payroll.get("date");
            data[3] = payroll.get("amount");
            data[4] = payroll.get("bonus");
            data[5] = payroll.get("deduction");
            data[6] = payroll.get("exchange_rate");
            data[7] = payroll.get("total_usd");
            data[8] = payroll.get("total_khr");
            pTable.addRow(data);
        }
    }

    /**
     * Creates new form Payroll
     */
    public Payroll() {
        initComponents();
        staffs = Employee.getAllEmployees();
        for (var staff : staffs) {
            cbStaff.addItem(new ComboItem(Helper.toUpperCase(staff.get("last_name").toString() + ' ' + Helper.toUpperCase(staff.get("first_name").toString())), staff.get("id").toString()));
        }
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbStaff = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDeduction = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtExchange = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dDate = new com.github.lgooddatepicker.components.DatePicker();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        payrollTable = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("Staff");
        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel2.add(jLabel1);

        cbStaff.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jPanel2.add(cbStaff);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("Amount");
        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel3.add(jLabel2);

        txtAmount.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtAmount.setText("250");
        jPanel3.add(txtAmount);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setText("Bonus");
        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel4.add(jLabel3);

        txtBonus.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtBonus.setText("0");
        jPanel4.add(txtBonus);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setText("Deduction");
        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel6.add(jLabel4);

        txtDeduction.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtDeduction.setText("0");
        jPanel6.add(txtDeduction);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setText("Exchange Rate");
        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel7.add(jLabel5);

        txtExchange.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtExchange.setText("4000");
        jPanel7.add(txtExchange);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jLabel6.setText("Date");
        jLabel6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jPanel8.add(jLabel6);

        dDate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jPanel8.add(dDate);

        jPanel5.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11, new java.awt.GridBagConstraints());

        jPanel19.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnSave.setText("Save");
        btnSave.setBackground(new java.awt.Color(0, 72, 217));
        btnSave.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel19.add(btnSave);

        btnUpdate.setText("Update");
        btnUpdate.setBackground(new java.awt.Color(35, 175, 121));
        btnUpdate.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel19.add(btnUpdate);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel9.add(jPanel19, gridBagConstraints);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        payrollTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Staff Name", "Date", "Amount", "Bonus", "Deduction", "Exchange Rate", "Total USD", "Total KHR"
            }
        ));
        payrollTable.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        payrollTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        payrollTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payrollTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(payrollTable);

        jPanel16.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payrollTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollTableMouseClicked
        int row = payrollTable.getSelectedRow();
        id = payrollTable.getValueAt(row, 0).toString();
        int index = 0;
        for (var staff : staffs) {
            String name = staff.get("first_name").toString() + ' ' + staff.get("last_name").toString();
            if (name.toLowerCase().equals(payrollTable.getValueAt(row, 1).toString().toLowerCase())) {
                cbStaff.setSelectedIndex(index);
            }
            index++;
        }
        txtAmount.setText(payrollTable.getValueAt(row, 3).toString());
        txtBonus.setText(payrollTable.getValueAt(row, 4).toString());
        txtDeduction.setText(payrollTable.getValueAt(row, 5).toString());
        txtExchange.setText(payrollTable.getValueAt(row, 6).toString());
        LocalDate thisDate = LocalDate.parse(payrollTable.getValueAt(row, 2).toString());
        dDate.setDate(thisDate);
    }//GEN-LAST:event_payrollTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String empId = ((ComboItem) cbStaff.getSelectedItem()).getValue();
        String date = dDate.getDate().toString();
        double amount = Double.parseDouble(txtAmount.getText());
        double bonus = Double.parseDouble(txtBonus.getText());
        double deduction = Double.parseDouble(txtDeduction.getText());
        int exchange_rate = Integer.parseInt(txtExchange.getText());
        double total_usd = amount + bonus - deduction;
        int total_khr = (int) Math.round(total_usd * exchange_rate);
        HashMap<String, String> message = PayrollClass.UpdatePayroll(id, empId, date, amount, bonus, deduction, exchange_rate, total_khr, total_usd);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String empId = ((ComboItem) cbStaff.getSelectedItem()).getValue();
        String date = dDate.getDate().toString();
        double amount = Double.parseDouble(txtAmount.getText());
        double bonus = Double.parseDouble(txtBonus.getText());
        double deduction = Double.parseDouble(txtDeduction.getText());
        int exchange_rate = Integer.parseInt(txtExchange.getText());
        double total_usd = amount + bonus - deduction;
        int total_khr = (int) Math.round(total_usd * exchange_rate);
        HashMap<String, String> message = PayrollClass.AddPayrolls(empId, date, amount, bonus, deduction, exchange_rate, total_khr, total_usd);
        JOptionPane.showMessageDialog(this, message.get("message"));
        if ("1".equals(message.get("code"))) {
            refreshTable();
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<ComboItem> cbStaff;
    private com.github.lgooddatepicker.components.DatePicker dDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable payrollTable;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtDeduction;
    private javax.swing.JTextField txtExchange;
    // End of variables declaration//GEN-END:variables
}
