/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Employee;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaswingdev.GradientDropdownMenu;
import javaswingdev.MenuEvent;
import javax.swing.*;

/**
 *
 * @author yarith
 */
public class UITabbar extends javax.swing.JFrame {
	private final int menuHeight;
	private final String[] menuAccount = {"Employee", "Account", "Attendance", "Overtime", "Role and Permission", "Payroll"};
	private final String[] menuBooking = {"Booing", "New Booking", "Manage Booking", "Manage Passenger"};
	private final String[] menuVehicle = {"Vehicle"};
	private final String[] menuFinancialAccount = {"Financial Account"};
	private final String[] menuTrip = {"Trip Management", "Location", "Route", "Trip"};
	private String[] menuReports = {"Reports"};

	// make sure image names in '/icons/<menu>.png' match to menu name
	private final ImageIcon[] iconsAccount = makeIconsArray(menuAccount);
	private final ImageIcon[] iconsBooking = makeIconsArray(menuBooking);
	private final ImageIcon[] iconsVehicle = makeIconsArray(menuVehicle);
	private final ImageIcon[] iconsFinancialAccount = makeIconsArray(menuFinancialAccount);
	private final ImageIcon[] iconsTrip = makeIconsArray(menuTrip);
	private final ImageIcon[] iconsReports = makeIconsArray(menuReports);

    public UITabbar() {
		GradientDropdownMenu menu = new GradientDropdownMenu();
		menuHeight = menu.getMenuHeight();
        initComponents();
		menu.setHeaderGradient(false);
		// menu colors
		menu.setGradientColor(new Color(67, 161, 163), new Color(67, 161, 163));
		menu.setBackground(new Color(52, 119, 120));
		menu.addItem(menuAccount, iconsAccount);
		menu.addItem(menuBooking, iconsBooking);
		menu.addItem(menuVehicle, iconsVehicle);
		menu.addItem(menuFinancialAccount, iconsFinancialAccount);
		menu.addItem(menuTrip, iconsTrip);
		menu.addItem(menuReports, iconsReports);
		menu.applay(this);
		menu.addEvent(new MenuEvent() {
			@Override
			public void selected(int index, int subIndex, boolean menuItem) {
				if (menuItem) {
					// load JFrame content according to menu name
					showForm(menu.getMenuNameAt(index, subIndex));
				}
			}
		});
    }
	void showForm(String str) {
		content.removeAll();
		if (str.compareTo("Account") == 0) {
			content.add(new Account().getContentPane());
		} // add more cases here
		else {
			System.out.println(str + " not found in showForm().");
			JOptionPane.showMessageDialog(this, str+" content is missing or not found.");
		}
		content.repaint();
		content.revalidate();
	}
	ImageIcon[] makeIconsArray(String... menus){
		ImageIcon[] iconsArr = new ImageIcon[menus.length];
		for (int i=0; i<menus.length; i++) {
			URL imageUrl = getClass().getResource("/icons/"+menus[i]+".png");
			if (imageUrl == null) {
				System.out.println("/icons/"+menus[i]+".png" + " doesn't exist.");
				continue;
			}
			ImageIcon icon = new ImageIcon(imageUrl);
			Image image = icon.getImage();
			int imgH = image.getHeight(this);
			int imgW = image.getWidth(this);
			if (imgH > imgW){
				image = image.getScaledInstance(25, -1, Image.SCALE_SMOOTH);
			}
			else {
				image = image.getScaledInstance(-1, 25, Image.SCALE_SMOOTH);
			}
			icon.setImage(image);
			iconsArr[i] = icon;
		}
		return iconsArr;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(20, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(20, menuHeight));
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1151, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UITabbar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
